// <auto-generated />
using Data_Acces_Layer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Acces_Layer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240208163214_updt122")]
    partial class updt122
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.Coin", b =>
                {
                    b.Property<int>("CoinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoinID"));

                    b.Property<string>("CoinBoild")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoinIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoinUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoinID");

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("EntityLayer.concrete.User_Login", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Words")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("User_Logins");
                });

            modelBuilder.Entity("EntityLayer.concrete.User_Wallet", b =>
                {
                    b.Property<int>("WalletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletID"));

                    b.Property<int>("CoinID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("WalletID");

                    b.HasIndex("CoinID");

                    b.HasIndex("UserID");

                    b.ToTable("User_Wallets");
                });

            modelBuilder.Entity("EntityLayer.concrete.User_Wallet", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.concrete.User_Login", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
